### ISSUE TITLE
mako.co.il

### ISSUE THREAD

**Issue by mako789** [easylist/EasyListHebrew#357]
it seems that mako blocks add block:
https://www.mako.co.il/news-channel12/channel_12_newscast?Partner=NewslobbyPrograms&sCh=31750a2610f26110&pId=173113804

**Comment by IsraeliUser** [comment]
Fixed. https://github.com/easylist/EasyListHebrew/commit/968dd1fc76a82ebeec67da6a37dd9af41443fbb7

**Comment by mako789** [comment]
still not working I see this:
![image](https://user-images.githubusercontent.com/78388546/106670644-fba03a80-65b5-11eb-8b6c-0271ac3803a2.png)

**Comment by IsraeliUser** [comment]
I can't reproduce.
Please use uBlock Origin (uninstall your current adblocker) and make sure that EasyList Hebrew is enabled.

**Comment by mako789** [comment]
I do have ublock origin, and easylist  hebrew is enabled. Did you click the play button on a video?
